{"issue_url": "https://api.github.com/repos/rails/rails/issues/382", "repo": "rails", "body": "`Thread#kill` and `Thread#raise` are basically impossible to use in a safe and reliable manner because the exceptions can come from anywhere and be of any type, Charles from jruby had a [great write up about it several years ago](http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html).  For example your particular patch won't help if the exception comes inside the `commit_db_transaction` method itself.\r\n\r\nI think attempting to be well behaved in the presence of `Thread#kill` is going to be too much effort to be worthwhile.\r\n", "_id": {"$oid": "52386109bd3543c1510122e7"}, "issue_id": 382, "url": "https://api.github.com/repos/rails/rails/issues/comments/1120717", "html_url": "https://github.com/rails/rails/pull/382#issuecomment-1120717", "updated_at": "2011-05-09T00:34:30Z", "user": {"subscriptions_url": "https://api.github.com/users/NZKoz/subscriptions", "events_url": "https://api.github.com/users/NZKoz/events{/privacy}", "repos_url": "https://api.github.com/users/NZKoz/repos", "gists_url": "https://api.github.com/users/NZKoz/gists{/gist_id}", "url": "https://api.github.com/users/NZKoz", "login": "NZKoz", "gravatar_id": "efa76b164a7de4a5730e4fa397cc4425", "html_url": "https://github.com/NZKoz", "following_url": "https://api.github.com/users/NZKoz/following{/other_user}", "received_events_url": "https://api.github.com/users/NZKoz/received_events", "organizations_url": "https://api.github.com/users/NZKoz/orgs", "avatar_url": "https://2.gravatar.com/avatar/efa76b164a7de4a5730e4fa397cc4425?d=https%3A%2F%2Fidenticons.github.com%2F85d8ce590ad8981ca2c8286f79f59954.png", "starred_url": "https://api.github.com/users/NZKoz/starred{/owner}{/repo}", "id": 197, "followers_url": "https://api.github.com/users/NZKoz/followers", "type": "User"}, "created_at": "2011-05-09T00:34:30Z", "id": 1120717, "owner": "rails"}
