{"body": "Yes, I had new_relic gem version 3.5.5.38.\r\nA couple hours ago I updated my gems and I was able to run my app in ruby v2 without this error", "url": "https://api.github.com/repos/rails/rails/issues/comments/15667988", "created_at": "2013-03-30T02:02:40Z", "html_url": "https://github.com/rails/rails/pull/9898#issuecomment-15667988", "updated_at": "2013-03-30T02:02:40Z", "repo": "rails", "issue_id": 9898, "user": {"following_url": "https://api.github.com/users/egjiri/following{/other_user}", "events_url": "https://api.github.com/users/egjiri/events{/privacy}", "organizations_url": "https://api.github.com/users/egjiri/orgs", "url": "https://api.github.com/users/egjiri", "gists_url": "https://api.github.com/users/egjiri/gists{/gist_id}", "html_url": "https://github.com/egjiri", "subscriptions_url": "https://api.github.com/users/egjiri/subscriptions", "avatar_url": "https://2.gravatar.com/avatar/f94e695f92db1450cb869d003b726b93?d=https%3A%2F%2Fidenticons.github.com%2F7b00668ff6a75a6c3de7d63b30c90981.png", "repos_url": "https://api.github.com/users/egjiri/repos", "received_events_url": "https://api.github.com/users/egjiri/received_events", "gravatar_id": "f94e695f92db1450cb869d003b726b93", "starred_url": "https://api.github.com/users/egjiri/starred{/owner}{/repo}", "login": "egjiri", "type": "User", "id": 1389310, "followers_url": "https://api.github.com/users/egjiri/followers"}, "owner": "rails", "_id": {"$oid": "5237e5b9bd3543c1510093c6"}, "id": 15667988, "issue_url": "https://api.github.com/repos/rails/rails/issues/9898"}
