{"issue_url": "https://api.github.com/repos/rails/rails/issues/6332", "repo": "rails", "body": "`bundle exec` is no fun in this case, we have two conflicting Gemfiles:\n\n- one from rails\n- second from the plugin test\n\nAnd only the second should be loaded during this exact test - which will be assured by my fix in #6318, the issue here is that the test was running before in context of the first Gemfile instead of second - now I have added additional tests to check `#{destination_root}/Gemfile.lock` which validates `bundle install` was run in proper context.\n", "_id": {"$oid": "52380b55bd3543c15100cff1"}, "issue_id": 6332, "url": "https://api.github.com/repos/rails/rails/issues/comments/5732085", "html_url": "https://github.com/rails/rails/pull/6332#issuecomment-5732085", "updated_at": "2012-05-16T02:04:17Z", "user": {"subscriptions_url": "https://api.github.com/users/mpapis/subscriptions", "events_url": "https://api.github.com/users/mpapis/events{/privacy}", "repos_url": "https://api.github.com/users/mpapis/repos", "gists_url": "https://api.github.com/users/mpapis/gists{/gist_id}", "url": "https://api.github.com/users/mpapis", "login": "mpapis", "gravatar_id": "3ec52ed58eb92026d86e62c39bdb7589", "html_url": "https://github.com/mpapis", "following_url": "https://api.github.com/users/mpapis/following{/other_user}", "received_events_url": "https://api.github.com/users/mpapis/received_events", "organizations_url": "https://api.github.com/users/mpapis/orgs", "avatar_url": "https://0.gravatar.com/avatar/3ec52ed58eb92026d86e62c39bdb7589?d=https%3A%2F%2Fidenticons.github.com%2F88265682f64ddb514c09888a3a37c511.png", "starred_url": "https://api.github.com/users/mpapis/starred{/owner}{/repo}", "id": 48054, "followers_url": "https://api.github.com/users/mpapis/followers", "type": "User"}, "created_at": "2012-05-16T02:04:17Z", "id": 5732085, "owner": "rails"}
