{"body": "Hey paneq,\r\n\r\nI tried to create a failing test case for this issue but I could not replicate the case.\r\n\r\nHere is the abstract of [my test](https://gist.github.com/818728).\r\n\r\nFrom my understanding you are overriding the destroy method in your class, doing some custom checks/logic, and then calling super so the original destroy runs? Please correct me if I am misunderstanding something.\r\n\r\nThanks,\r\n\r\nJosh\r\n\r\n", "url": "https://api.github.com/repos/rails/rails/issues/comments/755181", "created_at": "2011-02-09T20:45:27Z", "html_url": "https://github.com/rails/rails/pull/146#issuecomment-755181", "updated_at": "2011-02-09T20:45:27Z", "repo": "rails", "issue_id": 146, "user": {"following_url": "https://api.github.com/users/joshk/following{/other_user}", "events_url": "https://api.github.com/users/joshk/events{/privacy}", "organizations_url": "https://api.github.com/users/joshk/orgs", "url": "https://api.github.com/users/joshk", "gists_url": "https://api.github.com/users/joshk/gists{/gist_id}", "html_url": "https://github.com/joshk", "subscriptions_url": "https://api.github.com/users/joshk/subscriptions", "avatar_url": "https://0.gravatar.com/avatar/21b21efe14359ec323f9a70464b91e39?d=https%3A%2F%2Fidenticons.github.com%2F818cdcf067c824a4e34f9293de3b15a9.png", "repos_url": "https://api.github.com/users/joshk/repos", "received_events_url": "https://api.github.com/users/joshk/received_events", "gravatar_id": "21b21efe14359ec323f9a70464b91e39", "starred_url": "https://api.github.com/users/joshk/starred{/owner}{/repo}", "login": "joshk", "type": "User", "id": 8701, "followers_url": "https://api.github.com/users/joshk/followers"}, "owner": "rails", "_id": {"$oid": "5238672dbd3543c15101288b"}, "id": 755181, "issue_url": "https://api.github.com/repos/rails/rails/issues/146"}
