{"updated_at": "2012-09-18T07:55:07Z", "repo": "rails", "created_at": "2012-09-18T07:55:07Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/8644424", "id": 8644424, "issue_url": "https://api.github.com/repos/rails/rails/issues/7590", "issue_id": 7590, "user": {"repos_url": "https://api.github.com/users/bkuo/repos", "type": "User", "html_url": "https://github.com/bkuo", "starred_url": "https://api.github.com/users/bkuo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bkuo/subscriptions", "following_url": "https://api.github.com/users/bkuo/following{/other_user}", "gravatar_id": "9a43d1985eaeebd9afeab6c15f29709e", "organizations_url": "https://api.github.com/users/bkuo/orgs", "url": "https://api.github.com/users/bkuo", "gists_url": "https://api.github.com/users/bkuo/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/9a43d1985eaeebd9afeab6c15f29709e?d=https%3A%2F%2Fidenticons.github.com%2F107d96a4ad4d60e4a9951050468d399f.png", "id": 119251, "events_url": "https://api.github.com/users/bkuo/events{/privacy}", "login": "bkuo", "received_events_url": "https://api.github.com/users/bkuo/received_events", "followers_url": "https://api.github.com/users/bkuo/followers"}, "body": "The new tests pass on 3.2.0 -> 3.2.6.  It seems the bug was introduced as recently as 3.2.7.\n\n", "_id": {"$oid": "5237f9f2bd3543c15100b54f"}, "html_url": "https://github.com/rails/rails/pull/7590#issuecomment-8644424"}
