{"updated_at": "2013-05-07T17:39:33Z", "repo": "rails", "created_at": "2013-05-07T17:39:33Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/17557628", "id": 17557628, "issue_url": "https://api.github.com/repos/rails/rails/issues/10455", "issue_id": 10455, "user": {"repos_url": "https://api.github.com/users/tenderlove/repos", "type": "User", "html_url": "https://github.com/tenderlove", "starred_url": "https://api.github.com/users/tenderlove/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tenderlove/subscriptions", "following_url": "https://api.github.com/users/tenderlove/following{/other_user}", "gravatar_id": "f29327647a9cff5c69618bae420792ea", "organizations_url": "https://api.github.com/users/tenderlove/orgs", "url": "https://api.github.com/users/tenderlove", "gists_url": "https://api.github.com/users/tenderlove/gists{/gist_id}", "avatar_url": "https://1.gravatar.com/avatar/f29327647a9cff5c69618bae420792ea?d=https%3A%2F%2Fidenticons.github.com%2F7c78335a8924215ea5c22fda1aac7b75.png", "id": 3124, "events_url": "https://api.github.com/users/tenderlove/events{/privacy}", "login": "tenderlove", "received_events_url": "https://api.github.com/users/tenderlove/received_events", "followers_url": "https://api.github.com/users/tenderlove/followers"}, "body": "Sorry, I should have reviewed more closely, but this PR seems wrong.  I'm reverting the merge commit.  Can you check the pg tests and resubmit?  Specifically we're getting a failure on: `PostgresqlUUIDTestNilDefault#test_id_allows_default_override_via_nil`", "_id": {"$oid": "5237de9bbd3543c151008c2c"}, "html_url": "https://github.com/rails/rails/pull/10455#issuecomment-17557628"}
