{"updated_at": "2013-09-19T14:08:17Z", "repo": "rails", "created_at": "2013-09-19T14:08:17Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/24741070", "id": 24741070, "issue_url": "https://api.github.com/repos/rails/rails/issues/12285", "issue_id": 12285, "user": {"repos_url": "https://api.github.com/users/dasch/repos", "type": "User", "html_url": "https://github.com/dasch", "starred_url": "https://api.github.com/users/dasch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dasch/subscriptions", "following_url": "https://api.github.com/users/dasch/following{/other_user}", "gravatar_id": "a9cc05e6a7866e5fa9a7d107b5070174", "organizations_url": "https://api.github.com/users/dasch/orgs", "url": "https://api.github.com/users/dasch", "gists_url": "https://api.github.com/users/dasch/gists{/gist_id}", "avatar_url": "https://2.gravatar.com/avatar/a9cc05e6a7866e5fa9a7d107b5070174?d=https%3A%2F%2Fidenticons.github.com%2Fc6862d63b17d713ee14f3a405d9fde77.png", "id": 6351, "events_url": "https://api.github.com/users/dasch/events{/privacy}", "login": "dasch", "received_events_url": "https://api.github.com/users/dasch/received_events", "followers_url": "https://api.github.com/users/dasch/followers"}, "body": "The build failure seems to be due to a segfault :-/", "_id": {"$oid": "5240554cbd354364b9021064"}, "html_url": "https://github.com/rails/rails/pull/12285#issuecomment-24741070"}
