{"body": "I've fixed it, the problem was in `table_name.tr('/', '_')` --- the correct table name should have been taken from an attribute, and not obtained from the fixture path (ambiguously called `table_name`) by substitution. `fixtures.rb` looks scary, i am surprised it is working.\r\n\r\nI am running tests and updating the pull request.", "url": "https://api.github.com/repos/rails/rails/issues/comments/3277913", "created_at": "2011-12-27T01:11:35Z", "html_url": "https://github.com/rails/rails/pull/4153#issuecomment-3277913", "updated_at": "2011-12-27T01:11:35Z", "repo": "rails", "issue_id": 4153, "user": {"following_url": "https://api.github.com/users/alexeymuranov/following{/other_user}", "events_url": "https://api.github.com/users/alexeymuranov/events{/privacy}", "organizations_url": "https://api.github.com/users/alexeymuranov/orgs", "url": "https://api.github.com/users/alexeymuranov", "gists_url": "https://api.github.com/users/alexeymuranov/gists{/gist_id}", "html_url": "https://github.com/alexeymuranov", "subscriptions_url": "https://api.github.com/users/alexeymuranov/subscriptions", "avatar_url": "https://0.gravatar.com/avatar/63c72161fba6e27cb05c078651c5e969?d=https%3A%2F%2Fidenticons.github.com%2F063888cd6044f1607e923c4b12d136f8.png", "repos_url": "https://api.github.com/users/alexeymuranov/repos", "received_events_url": "https://api.github.com/users/alexeymuranov/received_events", "gravatar_id": "63c72161fba6e27cb05c078651c5e969", "starred_url": "https://api.github.com/users/alexeymuranov/starred{/owner}{/repo}", "login": "alexeymuranov", "type": "User", "id": 712698, "followers_url": "https://api.github.com/users/alexeymuranov/followers"}, "owner": "rails", "_id": {"$oid": "523f39adbd354364b9015ede"}, "id": 3277913, "issue_url": "https://api.github.com/repos/rails/rails/issues/4153"}
