{"updated_at": "2012-05-14T22:23:35Z", "repo": "rails", "created_at": "2012-05-14T22:23:35Z", "owner": "rails", "url": "https://api.github.com/repos/rails/rails/issues/comments/5703812", "id": 5703812, "issue_url": "https://api.github.com/repos/rails/rails/issues/6197", "issue_id": 6197, "user": {"repos_url": "https://api.github.com/users/blakesmith/repos", "type": "User", "html_url": "https://github.com/blakesmith", "starred_url": "https://api.github.com/users/blakesmith/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/blakesmith/subscriptions", "following_url": "https://api.github.com/users/blakesmith/following{/other_user}", "gravatar_id": "072d6a69039ba4ca7e4d9c8118225cf0", "organizations_url": "https://api.github.com/users/blakesmith/orgs", "url": "https://api.github.com/users/blakesmith", "gists_url": "https://api.github.com/users/blakesmith/gists{/gist_id}", "avatar_url": "https://0.gravatar.com/avatar/072d6a69039ba4ca7e4d9c8118225cf0?d=https%3A%2F%2Fidenticons.github.com%2F3316d81092ede6ad999c632bc1b57e4b.png", "id": 44368, "events_url": "https://api.github.com/users/blakesmith/events{/privacy}", "login": "blakesmith", "received_events_url": "https://api.github.com/users/blakesmith/received_events", "followers_url": "https://api.github.com/users/blakesmith/followers"}, "body": "For now, I've commented out the query explain threshold in my app, but this exception is a bad experience. Does anyone else have any input on this patch?", "_id": {"$oid": "52380cb5bd3543c15100d1bc"}, "html_url": "https://github.com/rails/rails/pull/6197#issuecomment-5703812"}
